language: php
php:
  - 7.1
before_script:
  - composer install --dev
script:
  - ./vendor/bin/phpunit --coverage-clover=build/log/clover.xml
  - make stan
  - make cs
after_success:
  - travis_retry php vendor/bin/coveralls -v
notifications:
  slack:
    secure: A4uHv6iCDudnshRWw9ifkyTrr2riQT+1jIt0PUYTcBWy1WmzHOmwymjSIYwdDBiF1kD25stxydPu3IKF15IF2lkPNTySxhQojZvhVQWcz9GUZahrQDjxWjzc2wKtS/pSNFq8n/4MRzZ3YLXNUwcjj/VvQoX7ccG8+EdoMx54R/KND/Tp6YHBx4fs5DQNeAfvl6vuD/xjqNH5Ugxb5CjZ0EVjVAAZvVcTHTEhtJXirSEUbs8bEeMTtQk0nxmmU4kzPULtlAheS9X8MXulLIIXFocYVjFK7pNBrSOUKL6rt4oilnrIMvArHtUmYw2m2oY7tEaOgw98URT6HfUpgKTReEajPVmeAXN4QMNJFDIJfMxNK77U+1Jlc/DdBGvDCIA6kevTE6QL/6OhDyasYn8jJvsPM4Qq913lxKXsIGbcrceRHTiJUM9Nl7/LDCIH/lsFhJEv71M277q53qk90AczUiRgv+HkDSOMic03HI3Z3pehV5OpeeetQ1uhWsBkQmKY3xu3/vsShrE2J1ylx8+WZg+egTkwUyykD2UW6Pg09SA6519uqtPbB/BaZb7mKmJ+8k03VnCSmTKGtEdxwdQX6JvDj41zeU6oAmWgQS5yap5W2t8NlGD9Byam5Ch3kvrVdk4gqsX1rj/avSz62RPI0wK9I1CF+KfuBTcbB4N+WKo=
